// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yigcijlzxhnqgiewmdsg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlpZ2Npamx6eGhucWdpZXdtZHNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NDU4NDQsImV4cCI6MjA1ODEyMTg0NH0.dEFN3_o3W_OII4QktHr1AI4oxohnQwBF6Q1Ccn7MYZo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);